---
version: '3.3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: postgres12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatgpt
      POSTGRES_PASSWORD: mypass
#     PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: myuser
#    volumes:
#      - ./psql-data:/var/lib/postgresql/data
